//object of abbreviations
//the abbreviations list has been sorted by length of the key, so that when it's iterated over, we replace the longest strings first
// e.g. 'United States of America' becomes 'U.S.A', not 'U.S. of Amer.'
// see directory for the unsorted list: abbreviations.json

//To do: see inside function

//ABBREVIATION LISTS
const quadgrams = {
    'united states of america': ['U.S.A.'],
    'united states of americas': ['U.S.A.']
}
const trigrams = {
    'district of columbia': ['D.C.'],
    "king's bench division": ["King's Bench Div."],
    "king's bench divisions": ["King's Bench Div."],
    'new south wales': ['New S. Wales'],
    'northwest territories': ['N.W. Territories'],
    "queen's bench division": ["Queen's Bench Div."]
}
const bigrams = {
    'british columbia': ['Brit. Columbia'],
    'british columbias': ['Brit. Columbia'],
    'new hampshire': ['New Hampsh.'],
    'new hampshires': ['New Hampsh.'],
    'new jersey': ['in full'],
    'new york': ['N.Y.', 'excl. as full work title, when in full'],
    'new yorker': ['in full'],
    'new yorks': ['N.Y.', 'excl. as full work title, when in full'],
    'new zealand': ['N.Z.'],
    'new zealands': ['N.Z.'],
    'north carolina': ['N. Carolina'],
    'north carolinas': ['N. Carolina'],
    'north dakota': ['N. Dakota'],
    'north dakotas': ['N. Dakota'],
    'north east': ['in full', 'exc. when with a place-name, when > N.E.'],
    'north eastern': ['in full', 'exc. when with a place-name, when > N.E.'],
    'north territories': ['N. Territory'],
    'north territory': ['N. Territory'],
    'north west': ['in full', 'exc. when with a place-name, when > N.W.'],
    'north western': ['in full', 'exc. when with a place-name, when > N.W.'],
    'northwest territories': ['N.W. Territories'],
    'old english': ['Old Eng.'],
    'old englishes': ['Old Eng.'],
    'south australia': ['S. Austral.'],
    'south australias': ['S. Austral.'],
    'south carolina': ['S. Carolina'],
    'south carolinas': ['S. Carolina'],
    'south dakota': ['S. Dakota'],
    'south dakotas': ['S. Dakota'],
    'south east': ['in full', 'exc. when with a place-name, when > S.E.'],
    'south eastern': ['in full', 'exc. when with a place-name, when > S.E.'],
    'south west': ['in full', 'exc. when with a place-name, when > S.W.'],
    'south western': ['in full', 'exc. when with a place-name, when > S.W.'],
    'united states': ['U.S.'],
    'west australia': ['W. Austral.'],
    'west australias': ['W. Austral.'],
    'west virginia': ['in full', 'exc. when with a place-name, when > W. Va.'],
    'west virginias': ['in full', 'exc. when with a place-name, when > W. Va.']
}
const unigrams = {
    'abbey': ['in full'],
    'abbreviation': ['abbrev.'],
    'abbreviations': ['abbrev.'],
    'absolute': ['in full'],
    'abstract': ['abstr.'],
    'abstracts': ['abstr.'],
    'academe': ['in full'],
    'academic': ['acad.'],
    'academician': ['in full'],
    'academics': ['acad.'],
    'academies': ['acad.'],
    'academy': ['acad.'],
    'acceptance': ['accept.'],
    'acceptances': ['accept.'],
    'accommodation': ['accomm.'],
    'accommodations': ['accomm.'],
    'account': ['acct.'],
    'accounts': ['accts.'],
    'accumulated': ['in full'],
    'accumulation': ['in full'],
    'accumulator': ['in full'],
    'additional': ['addit.'],
    'address': ['addr.'],
    'addresses': ['addr.'],
    'administration': ['admin.'],
    'administrations': ['admin.'],
    'admonition': ['admon.'],
    'admonitions': ['admon.'],
    'adulteration': ['in full'],
    'advanced': ['adv.'],
    'advances': ['adv.'],
    'adventure': ['in full'],
    'advertisement': ['advt.'],
    'advertisements': ['advts.'],
    'advertiser': ['in full'],
    'aerodynamic': ['in full'],
    'aerodynamics': ['aerodynam.'],
    'aeronautic': ['aeronaut.'],
    'aeronautical': ['aeronaut.'],
    'aeronauticals': ['aeronaut.'],
    'aeronautics': ['aeronaut.'],
    'africa': ['Afr.'],
    'african': ['Afr.'],
    'africans': ['Afr.'],
    'africas': ['Afr.'],
    'against': ['in full'],
    'agricultural': ['agric.'],
    'agriculturalist': ['in full'],
    'agriculturals': ['agric.'],
    'agriculture': ['agric.'],
    'agricultures': ['agric.'],
    'agriculturist': ['in full'],
    'aircraft': ['in full'],
    'alliterative': ['allit.'],
    'alliteratives': ['allit.'],
    'almanack': ['in full'],
    'alphabet': ['in full'],
    'alphabetic': ['in full'],
    'alphabetical': ['alphabet.'],
    'alphabeticals': ['alphabet.'],
    'amateur': ['in full'],
    'america': ['Amer.'],
    'american': ['Amer.'],
    'americans': ['Amer.'],
    'americas': ['Amer.'],
    'analog': ['in full'],
    'analogue': ['in full'],
    'analogy': ['in full'],
    'analyses': ['anal.'],
    'analysis': ['anal.'],
    'analytical': ['analyt.'],
    'analyticals': ['analyt.'],
    'anatomic': ['anat.'],
    'anatomical': ['anat.'],
    'anatomicals': ['anat.'],
    'anatomies': ['anat.'],
    'anatomist': ['in full'],
    'anatomized': ['in full'],
    'anatomy': ['anat.'],
    'ancient': ['anc.'],
    'ancients': ['anc.'],
    'anecdote': ['anecd.'],
    'anecdotes': ['anecd.'],
    'anglo-saxon': ['in full'],
    'animadversions': ['in full'],
    'animal': ['in full'],
    'annal': ['ann.'],
    'annals': ['ann.'],
    'anniversaries': ['anniv.'],
    'anniversary': ['anniv.'],
    'annotation': ['annot.'],
    'annotations': ['annot.'],
    'annual': ['ann.'],
    'annuals': ['ann.'],
    'answer': ['in full'],
    'anthropological': ['anthropol.'],
    'anthropologicals': ['anthropol.'],
    'anthropologies': ['anthropol.'],
    'anthropologist': ['in full'],
    'anthropology': ['anthropol.'],
    'antidote': ['in full'],
    'antient': ['in full'],
    'antiquities': ['antiq.'],
    'antiquity': ['antiq.'],
    'apocalyptic': ['apoc.'],
    'apocalyptical': ['apoc.'],
    'apocalypticals': ['apoc.'],
    'apocalyptics': ['apoc.'],
    'apologetic': ['apol.'],
    'apologetical': ['apol.'],
    'apologeticals': ['apol.'],
    'apologetics': ['apol.'],
    'apologies': ['apol.'],
    'apologist': ['in full'],
    'apology': ['apol.'],
    'appendices': ['app.'],
    'appendix': ['app.'],
    'appendixes': ['app.'],
    'application': ['applic.'],
    'applications': ['applic.'],
    'applied': ['appl.'],
    'approach': ['in full'],
    'appropriate': ['in full'],
    'appropriation': ['in full'],
    'archaic': ['in full'],
    'archbishop': ['in full', 'exc. when followed by personal name, when > Abp.'],
    'archipelago': ['archipel.'],
    'archipelagos': ['archipel.'],
    'architect': ['in full'],
    'architectural': ['archit.'],
    'architecturals': ['archit.'],
    'architecture': ['archit.'],
    'architectures': ['archit.'],
    'archive': ['arch.'],
    'archives': ['arch.'],
    'argument': ['in full'],
    'arithmetic': ['arithm.'],
    'arithmetical': ['arithm.'],
    'arithmeticals': ['arithm.'],
    'arithmetics': ['arithm.'],
    'arrangement': ['arrangem.'],
    'arrangements': ['arrangem.'],
    'article': ['in full'],
    'articulate': ['in full'],
    'articulated': ['artic.'],
    'articulation': ['artic.'],
    'articulations': ['artic.'],
    'artificial': ['artific.'],
    'artificials': ['artific.'],
    'assassination': ['in full'],
    'assign': ['in full'],
    'assignation': ['in full'],
    'assigned': ['in full'],
    'assignment': ['in full'],
    'assistance': ['in full'],
    'assistant': ['in full'],
    'association': ['assoc.'],
    'associations': ['assoc.'],
    'astronaut': ['in full'],
    'astronautic': ['astronaut.'],
    'astronautical': ['astronaut.'],
    'astronauticals': ['astronaut.'],
    'astronautics': ['astronaut.'],
    'astronomic': ['astron.'],
    'astronomical': ['astron.'],
    'astronomicals': ['astron.'],
    'astronomics': ['astron.'],
    'astronomies': ['astron.'],
    'astronomist': ['in full'],
    'astronomy': ['astron.'],
    'aurelius': ['in full'],
    'australia': ['Austral.'],
    'australian': ['Austral.'],
    'australians': ['Austral.'],
    'australias': ['Austral.'],
    'autobiographic': ['autobiogr.'],
    'autobiographical': ['autobiogr.'],
    'autobiographicals': ['autobiogr.'],
    'autobiographics': ['autobiogr.'],
    'autobiographies': ['autobiogr.'],
    'autobiography': ['autobiogr.'],
    'automated': ['in full'],
    'automatic': ['in full'],
    'automation': ['in full'],
    'automobile': ['in full'],
    'bacterial': ['in full'],
    'bacteriologies': ['bacteriol.'],
    'bacteriologist': ['in full'],
    'bacteriology': ['bacteriol.'],
    'ballad': ['in full'],
    'barbarian': ['in full'],
    'baroness': ['in full'],
    'behaviour': ['in full'],
    'berkshire': ['Berks', 'exc. when Massachusetts, then Berkshire County'],
    'biochemical': ['biochem.'],
    'biochemicals': ['biochem.'],
    'biochemist': ['in full'],
    'biochemistries': ['biochem.'],
    'biochemistry': ['biochem.'],
    'biographer': ['in full'],
    'biographia': ['biogr.'],
    'biographical': ['biogr.'],
    'biographicals': ['biogr.'],
    'biographies': ['biogr.'],
    'biography': ['biogr.'],
    'biological': ['biol.'],
    'biologicals': ['biol.'],
    'biologies': ['biol.'],
    'biologist': ['in full'],
    'biology': ['biol.'],
    'biomedical': ['biomed.'],
    'biomedicals': ['biomed.'],
    'biomedicine': ['biomed.'],
    'biomedicines': ['biomed.'],
    'biophysical': ['in full'],
    'biscuit': ['in full'],
    'bishop': ['in full', 'exc. when followed by personal name, when > Bp.'],
    'boke': ['in full'],
    'book': ['bk.'],
    'booke': ['bk.'],
    'bookes': ['bks.'],
    'books': ['bks.'],
    'borough': ['in full'],
    'botanic': ['bot.'],
    'botanical': ['bot.'],
    'botanicals': ['bot.'],
    'botanics': ['bot.'],
    'botanies': ['bot.'],
    'botanist': ['in full'],
    'botany': ['bot.'],
    'breakfast': ['in full'],
    'breviary': ['in full'],
    'breviat': ['in full'],
    'brevis': ['in full'],
    'brevities': ['in full'],
    'brevium': ['in full'],
    'brevius': ['in full'],
    'brewer': ['in full'],
    'brewery': ['in full'],
    'brewing': ['in full'],
    'britain': ['Brit.'],
    'britains': ['Brit.'],
    'british': ['Brit.'],
    'britishes': ['Brit.'],
    'broadcasting': ['in full'],
    'buckinghamshire': ['Bucks.'],
    'buckinghamshires': ['Bucks.'],
    'bulk': ['in full'],
    'bulletin': ['bull.'],
    'bulletins': ['bull.'],
    'business': ['in full'],
    'calcium': ['in full'],
    'calculating': ['in full'],
    'calculus': ['in full'],
    'calendar': ['cal.'],
    'calendars': ['cal.'],
    'california': ['Calif.'],
    'californias': ['Calif.'],
    'cambridge': ['Cambr.'],
    'cambridges': ['Cambr.'],
    'camera': ['in full'],
    'canada': ['in full'],
    'canadian': ['Canad.'],
    'canadians': ['Canad.'],
    'captain': ['in full', 'exc. when with a name as a title, when > Capt.'],
    'cartographer': ['in full'],
    'cartographic': ['cartogr.'],
    'cartographics': ['cartogr.'],
    'cartographies': ['cartogr.'],
    'cartography': ['cartogr.'],
    'catalogue': ['catal.'],
    'catalogues': ['catal.'],
    'catechism': ['catech.'],
    'catechisms': ['catech.'],
    'cathedral': ['in full'],
    'catholic': ['in full'],
    'catholics': ['in full'],
    'central': ['in full'],
    'centuries': ['cent.'],
    'century': ['cent.'],
    'certain': ['in full'],
    'certificate': ['in full'],
    'certification': ['in full'],
    'certified': ['in full'],
    'certify': ['in full'],
    'chapter': ['in full'],
    'character': ['char.'],
    'characters': ['char.'],
    'chemical': ['chem.'],
    'chemicals': ['chem.'],
    'chemist': ['in full'],
    'chemistries': ['chem.'],
    'chemistry': ['chem.'],
    'chirurgical': ['chirurg.'],
    'chirurgicals': ['chirurg.'],
    'chirurgies': ['chirurg.'],
    'chirurgy': ['chirurg.'],
    'christ': ['in full'],
    'christian': ['in full'],
    'christianity': ['in full'],
    'chronicle': ['chron.'],
    'chronicles': ['chrons.'],
    'church': ['in full'],
    'churches': ['in full'],
    'churchwarden': ['in full'],
    'cinema': ['in full'],
    'cinematographer': ['in full'],
    'cinematographic': ['cinematogr.'],
    'cinematographics': ['cinematogr.'],
    'cinematographies': ['cinematogr.'],
    'cinematography': ['cinematogr.'],
    'civil': ['in full'],
    'civilisation': ['in full'],
    'civilised': ['in full'],
    'civility': ['in full'],
    'civilization': ['in full'],
    'civilized': ['in full'],
    'classic': ['in full'],
    'classical': ['in full'],
    'classification': ['classif.'],
    'classifications': ['classif.'],
    'clerical': ['in full'],
    'clinic': ['in full'],
    'clinical': ['clin.'],
    'collected': ['coll.'],
    'collection': ['coll.'],
    'collections': ['coll.'],
    'collective': ['in full'],
    'college': ['in full', 'exc. when prec. by name, when > Coll.'],
    'colleges': ['in full', 'exc. when prec. by name, when > Coll.'],
    'colonel': ['col.'],
    'colonels': ['col.'],
    'colonial': ['in full'],
    'colony': ['in full'],
    'colour': ['in full'],
    'coloured': ['in full'],
    'commentaries': ['comm.'],
    'commentary': ['comm.'],
    'commerce': ['in full'],
    'commercial': ['commerc.'],
    'commission': ['comm.'],
    'commissions': ['comm.'],
    'committee': ['comm.'],
    'committees': ['comm.'],
    'common': ['in full'],
    'commonwealth': ['commonw.'],
    'commonwealths': ['commonw.'],
    'communicant': ['in full'],
    'communication': ['in full'],
    'communion': ['in full'],
    'companion': ['compan.'],
    'companions': ['compan.'],
    'comparative': ['compar.'],
    'comparison': ['compar.'],
    'comparisons': ['compar.'],
    'compendia': ['compend.'],
    'compendious': ['compend.'],
    'compendium': ['compend.'],
    'complaint': ['in full'],
    'compleat': ['compl.'],
    'complete': ['compl.'],
    'comprehensive': ['in full'],
    'compressed': ['in full'],
    'compromise': ['in full'],
    'computation': ['in full'],
    'computational': ['in full'],
    'compute': ['in full'],
    'computer': ['in full'],
    'computing': ['in full'],
    'computus': ['in full'],
    'concerning': ['conc.'],
    'concise': ['conc.'],
    'conclusion': ['concl.'],
    'conclusions': ['concl.'],
    'concrete': ['in full'],
    'conference': ['conf.'],
    'conferences': ['conf.'],
    'confessio': ['in full'],
    'confession': ['in full'],
    'confessional': ['in full'],
    'confessor': ['in full'],
    'confidential': ['in full'],
    'conflict': ['in full'],
    'confutation': ['confut.'],
    'confutations': ['confut.'],
    'congregation': ['in full'],
    'congress': ['congr.'],
    'congresses': ['congr.'],
    'congressional': ['congress.'],
    'conscience': ['in full'],
    'consider': ['in full'],
    'considerate': ['in full'],
    'consideration': ['in full'],
    'consolation': ['consol.'],
    'consolations': ['consol.'],
    'constitution': ['constit.'],
    'constitutional': ['constit.'],
    'constitutions': ['constit.'],
    'construction': ['constr.'],
    'constructions': ['constr.'],
    'contemplate': ['contempl.'],
    'contemplates': ['contempl.'],
    'contemplation': ['contempl.'],
    'contemplational': ['contempl.'],
    'contemplations': ['contempl.'],
    'contemplative': ['contempl.'],
    'contemporary': ['contemp.'],
    'continuation': ['contin.'],
    'continuations': ['contin.'],
    'continued': ['in full'],
    'contradiction': ['contradict.'],
    'contradictions': ['contradict.'],
    'contribution': ['contrib.'],
    'contributions': ['contrib.'],
    'controversial': ['controv.'],
    'controversies': ['controv.'],
    'controversy': ['controv.'],
    'convention': ['convent.'],
    'conventions': ['convent.'],
    'conversation': ['conversat.'],
    'conversations': ['conversat.'],
    'conversion': ['in full'],
    'cornish': ['in full'],
    'cornwall': ['in full'],
    'correspondence': ['corr.'],
    'correspondences': ['corr.'],
    'countess': ['in full'],
    'countesse': ['in full'],
    'court': ['in full'],
    'craftsmanship': ['in full'],
    'creation': ['in full'],
    'criminal': ['in full'],
    'critic': ['in full'],
    'critical': ['crit.'],
    'criticism': ['crit.'],
    'criticisms': ['crit.'],
    'cultivated': ['in full'],
    'cultivation': ['cultiv.'],
    'cultivations': ['cultiv.'],
    'cultivator': ['in full'],
    'curiosities': ['in full'],
    'currency': ['in full'],
    'cyclopaedia': ['cycl.'],
    'cyclopaedias': ['cycl.'],
    'cytological': ['cytol.'],
    'cytologies': ['cytol.'],
    'cytologist': ['in full'],
    'cytology': ['cytol.'],
    'danger': ['in full'],
    'daughter': ['in full'],
    'debate': ['deb.'],
    'debates': ['deb.'],
    'declaration': ['declar.'],
    'declarations': ['declar.'],
    'decline': ['in full'],
    'dedication': ['ded.'],
    'dedications': ['ded.'],
    'defence': ['def.'],
    'defences': ['def.'],
    'defense': ['def.'],
    'defenses': ['def.'],
    'definition': ['in full'],
    'deliverance': ['deliv.'],
    'deliverances': ['deliv.'],
    'delivery': ['in full'],
    'democracy': ['in full'],
    'democrat': ['in full'],
    'democratic': ['in full'],
    'demonstration': ['demonstr.'],
    'demonstrations': ['demonstr.'],
    'dental': ['in full'],
    'dentist': ['in full'],
    'dentistry': ['in full'],
    'department': ['dept.'],
    'departments': ['dept.'],
    'description': ['descr.'],
    'descriptions': ['descr.'],
    'descriptive': ['in full'],
    'destruction': ['destr.'],
    'destructions': ['destr.'],
    'development': ['devel.'],
    'developmental': ['in full'],
    'developments': ['devel.'],
    'diagnosing': ['in full'],
    'diagnosis': ['in full'],
    'diagnostic': ['in full'],
    'dialect': ['dial.'],
    'dialects': ['dial.'],
    'dialogue': ['in full'],
    'dictionaries': ['dict.'],
    'dictionary': ['dict.'],
    'different': ['in full'],
    'differential': ['in full'],
    'difficulties': ['diffic.'],
    'difficulty': ['diffic.'],
    'direction': ['direct.'],
    'directions': ['direct.'],
    'directory': ['in full'],
    'discourse': ['disc.'],
    'discourses': ['disc.'],
    'discoveries': ['discov.'],
    'discovery': ['discov.'],
    'discrimination': ['discrim.'],
    'discriminations': ['discrim.'],
    'discussion': ['discuss.'],
    'discussions': ['discuss.'],
    'disease': ['dis.'],
    'diseases': ['dis.'],
    'disorder': ['in full'],
    'dispatch': ['disp.'],
    'dispatches': ['disp.'],
    'dispensatory': ['in full'],
    'disquisition': ['disquis.'],
    'disquisitions': ['disquis.'],
    'dissertation': ['diss.'],
    'dissertations': ['diss.'],
    'district': ['in full'],
    'diversity': ['in full'],
    'divine': ['in full'],
    'divinity': ['in full'],
    'division': ['div.'],
    'divisions': ['div.'],
    'doctor': ['in full', 'exc. with surname, when > Dr.'],
    'doctors': ['in full', 'exc. with surname, when > Dr.'],
    'doctrine': ['doctr.'],
    'doctrines': ['doctr.'],
    'document': ['in full'],
    'domestic': ['domest.'],
    'dramatic': ['in full'],
    'duke': ['in full'],
    'east': ['in full', 'exc. with place-name, when > E.'],
    'eastern': ['in full', 'exc. with place-name, when > E.'],
    'ecclesiastic': ['eccl.'],
    'ecclesiastical': ['eccl.'],
    'ecological': ['ecol.'],
    'ecologies': ['ecol.'],
    'ecologist': ['in full'],
    'ecology': ['ecol.'],
    'economic': ['econ.'],
    'economical': ['econ.'],
    'economics': ['econ.'],
    'economies': ['econ.'],
    'economist': ['in full'],
    'economy': ['econ.'],
    'edinburgh': ['Edinb.'],
    'edinburghs': ['Edinb.'],
    'education': ['educ.'],
    'educational': ['educ.'],
    'educations': ['educ.'],
    'electrical': ['electr.'],
    'electricals': ['electr.'],
    'electrician': ['in full'],
    'electricities': ['electr.'],
    'electricity': ['electr.'],
    'electronic': ['in full'],
    'element': ['elem.'],
    'elemental': ['in full'],
    'elementary': ['elem.'],
    'elements': ['elem.'],
    'elizabethan': ['in full'],
    'embryological': ['embryol.'],
    'embryologies': ['embryol.'],
    'embryologist': ['in full'],
    'embryology': ['embryol.'],
    'encyclopaedia': ['encycl.'],
    'encyclopaedias': ['encycl.'],
    'encyclopaedic': ['encycl.'],
    'engine': ['in full'],
    'engineer': ['in full'],
    'engineering': ['engin.'],
    'england': ['Eng.'],
    "england's": ['in full'],
    'englands': ['Eng.'],
    'english': ['Eng.'],
    'englishes': ['Eng.'],
    'englishman': ['in full'],
    'engraver': ['in full'],
    'engraving': ['in full'],
    'enquiries': ['enq.'],
    'enquiry': ['enq.'],
    'enthusiasm': ['in full'],
    'entomological': ['entomol.'],
    'entomologies': ['entomol.'],
    'entomologist': ['in full'],
    'entomology': ['entomol.'],
    'environment': ['in full'],
    'environmental': ['in full'],
    'epigram': ['in full'],
    'epilogue': ['epil.'],
    'epilogues': ['epil.'],
    'epistle': ['Ep.'],
    'epistles': ['Ep.'],
    'epitome': ['in full'],
    'equation': ['in full'],
    'equatorial': ['in full'],
    'equipment': ['equipm.'],
    'equipments': ['equipm.'],
    'essay': ['ess.'],
    'essays': ['ess.'],
    'essential': ['essent.', 'exc. if a noun, when in full'],
    'estate': ['in full'],
    'estimate': ['in full'],
    'etymological': ['etymol.'],
    'etymologies': ['etymol.'],
    'etymologist': ['in full'],
    'etymology': ['etymol.'],
    'europe': ['in full'],
    'european': ['in full'],
    'evaluation': ['eval.'],
    'evaluations': ['eval.'],
    'evening': ['in full'],
    'evidence': ['evid.'],
    'evidences': ['evid.'],
    'evolution': ['evol.'],
    'evolutionary': ['in full'],
    'evolutionist': ['in full'],
    'evolutions': ['evol.'],
    'exaltation': ['exalt.'],
    'exaltations': ['exalt.'],
    'examination': ['exam.'],
    'examinations': ['exam.'],
    'examined': ['in full'],
    'excellence': ['in full'],
    'excellency': ['in full'],
    'excellent': ['in full'],
    'exchange': ['in full'],
    'excommunication': ['excommun.'],
    'excommunications': ['excommun.'],
    'exercise': ['in full'],
    'exhibit': ['exhib.'],
    'exhibited': ['exhib.'],
    'exhibition': ['exhib.'],
    'exhibitions': ['exhib.'],
    'exhibits': ['exhib.'],
    'exhortation': ['exhort.'],
    'exhortations': ['exhort.'],
    'expedition': ['exped.'],
    'expeditions': ['exped.'],
    'experience': ['in full'],
    'experiment': ['exper.'],
    'experimental': ['exper.'],
    'experimentation': ['exper.'],
    'experimentations': ['exper.'],
    'experiments': ['exper.'],
    'explanation': ['explan.'],
    'explanations': ['explan.'],
    'explication': ['explic.'],
    'explications': ['explic.'],
    'exploration': ['explor.'],
    'explorations': ['explor.'],
    'exposition': ['expos.'],
    'expositions': ['expos.'],
    'express': ['in full'],
    'facsimile': ['in full'],
    'familiar': ['in full'],
    'family': ['in full'],
    'father': ['in full', "exc. as priest's title, when > Fr."],
    'fiction': ['in full'],
    'figure': ['in full'],
    'finance': ['in full'],
    'financial': ['in full'],
    'footprint': ['footpr.'],
    'footprints': ['footpr.'],
    'foreign': ['in full'],
    'fortnightly': ['fortn.'],
    'fortune': ['in full'],
    'foundation': ['found.'],
    'foundations': ['found.'],
    'fracture': ['in full'],
    'fragment': ['fragm.'],
    'fragments': ['fragm.'],
    'france': ['in full'],
    'fraternal': ['in full'],
    'french': ['in full'],
    'friend': ['in full'],
    'friendly': ['in full'],
    'from': ['in full'],
    'function': ['in full'],
    'fundamental': ['fund.'],
    'fundamentals': ['fund.'],
    'furniture': ['furnit.'],
    'furnitures': ['furnit.'],
    'garden': ['in full'],
    'gardener': ['in full'],
    'gardening': ['in full'],
    'gazette': ['gaz.'],
    'gazettes': ['gaz.'],
    'genealogical': ['geneal.'],
    'genealogies': ['geneal.'],
    'genealogist': ['in full'],
    'genealogy': ['geneal.'],
    'general': ['gen.'],
    'generation': ['in full'],
    'generative': ['in full'],
    'gentleman': ['in full'],
    "gentleman's": ['in full'],
    'gentlemen': ['in full'],
    "gentlemen's": ['in full'],
    'geographer': ['in full'],
    'geographic': ['in full'],
    'geographical': ['geogr.'],
    'geographies': ['geogr.'],
    'geography': ['geogr.'],
    'geological': ['geol.'],
    'geologies': ['geol.'],
    'geologist': ['in full'],
    'geology': ['geol.'],
    'geometric': ['geom.'],
    'geometrical': ['geom.'],
    'geometricals': ['geom.'],
    'geometrics': ['geom.'],
    'geometries': ['geom.'],
    'geometry': ['geom.'],
    'german': ['in full'],
    'germanic': ['in full'],
    'glossaries': ['gloss.'],
    'glossary': ['gloss.'],
    'good': ['in full'],
    'gospel': ['in full'],
    'government': ['govt.'],
    'governments': ['govts.'],
    'grammar': ['gram.'],
    'grammars': ['gram.'],
    'great': ['in full'],
    'greek': ['in full'],
    'hand-book': ['hand-bk.'],
    'hand-books': ['hand-bks.'],
    'handbook': ['handbk.'],
    'handbooks': ['handbks.'],
    'heaven': ['in full'],
    'heavenly': ['in full'],
    'hebrew': ['in full'],
    'hebrides': ['in full'],
    'heraldry': ['in full'],
    'hertfordshire': ['Herts.'],
    'hertfordshires': ['Herts.'],
    'highlands': ['in full'],
    'histological': ['histol.'],
    'historian': ['in full'],
    'historic': ['hist.'],
    'historical': ['hist.'],
    'historie': ['hist.'],
    'histories': ['hist.'],
    'history': ['hist.'],
    'holiday': ['in full'],
    'horticultural': ['hort.'],
    'horticulturalist': ['in full'],
    'horticulture': ['hort.'],
    'horticultures': ['hort.'],
    'hospital': ['hosp.'],
    'hospitals': ['hosp.'],
    'household': ['househ.'],
    'households': ['househ.'],
    'housekeeping': ['housek.'],
    'housewife': ['in full'],
    'human': ['in full'],
    'humanities': ['in full'],
    'husband': ['in full'],
    'husbandry': ['in full'],
    'hydraulic': ['hydraul.'],
    'hydrological': ['hydrol.'],
    'hydrologies': ['hydrol.'],
    'hydrologist': ['in full'],
    'hydrology': ['hydrol.'],
    'hygiene': ['in full'],
    'hygienic': ['in full'],
    'hygienist': ['in full'],
    'ideological': ['ideol.'],
    'ideologies': ['ideol.'],
    'ideology': ['ideol.'],
    'illustrated': ['illustr.'],
    'illustration': ['illustr.'],
    'illustrations': ['illustr.'],
    'illustrative': ['illustr.'],
    'illustrator': ['in full'],
    'impression': ['in full'],
    'improved': ['in full'],
    'improvement': ['improvem.'],
    'improvements': ['improvem.'],
    'inaugural': ['inaug.'],
    'inaugurals': ['inaug.'],
    'india': ['in full'],
    'indian': ['in full'],
    'indo-european': ['in full'],
    'industrial': ['industr.'],
    'industry': ['in full'],
    'infant': ['in full'],
    'influence': ['infl.'],
    'influences': ['infl.'],
    'information': ['in full'],
    'innocence': ['in full'],
    'innocent': ['in full'],
    'inorganic': ['inorg.'],
    'inquiries': ['inq.'],
    'inquiry': ['inq.'],
    'instantaneous': ['in full'],
    'institute': ['inst.'],
    'institutes': ['inst.'],
    'institution': ['inst.'],
    'institutions': ['inst.'],
    'instruction': ['instr.'],
    'instructions': ['instr.'],
    'instrument': ['in full'],
    'intellectual': ['intellect.'],
    'intellectuals': ['intellect.'],
    'intelligence': ['in full'],
    'intelligent': ['in full'],
    'international': ['internat.'],
    'internationals': ['internat.'],
    'interpretation': ['interpr.'],
    'interpretations': ['interpr.'],
    'interpreter': ['in full'],
    'introduction': ['introd.'],
    'introductions': ['introd.'],
    'introductories': ['introd.'],
    'introductory': ['introd.'],
    'inventory': ['in full'],
    'invertebrate': ['invertebr.'],
    'invertebrates': ['invertebr.'],
    'investigation': ['investig.'],
    'investigations': ['investig.'],
    'investigative': ['in full'],
    'investment': ['investm.'],
    'investments': ['investm.'],
    'ireland': ['in full'],
    'island': ['in full'],
    'isles': ['in full'],
    'italian': ['Ital.'],
    'italians': ['Ital.'],
    'japan': ['in full'],
    'japanese': ['in full'],
    'journal': ['jrnl.'],
    'journals': ['jrnls.'],
    'journey': ['in full'],
    'junior': ['in full'],
    'jurisdiction': ['jurisdict.'],
    'jurisdictions': ['jurisdict.'],
    'jurisprudence': ['jurispr.'],
    'jurisprudences': ['jurispr.'],
    'justification': ['justif.'],
    'justifications': ['justif.'],
    'juvenile': ['in full'],
    'king': ['in full'],
    'kingdom': ['in full'],
    'knowledge': ['knowl.'],
    'knowledges': ['knowl.'],
    'laboratories': ['lab.'],
    'laboratory': ['lab.'],
    'lamentable': ['in full'],
    'lamentation': ['lament.'],
    'lamentations': ['lament.'],
    'lancashire': ['Lancs.'],
    'lancashires': ['Lancs.'],
    'language': ['lang.'],
    'languages': ['langs.'],
    'latin': ['Lat.'],
    'latins': ['Lat.'],
    'latitude': ['in full'],
    'lecture': ['lect.'],
    'lectures': ['lect.'],
    'legend': ['in full'],
    'leicestershire': ['Leics.'],
    'leicestershires': ['Leics.'],
    'lesson': ['in full'],
    'letter': ['let.'],
    'letters': ['lett.'],
    'lexicon': ['in full'],
    'librarian': ['in full'],
    'libraries': ['libr.'],
    'library': ['libr.'],
    'lincolnshire': ['Lincs.'],
    'lincolnshires': ['Lincs.'],
    'linguistic': ['ling.'],
    'linguistics': ['ling.'],
    'linnean': ['Linn.'],
    'linneans': ['Linn.'],
    'literary': ['lit.'],
    'literature': ['lit.'],
    'literatures': ['lit.'],
    'liturgical': ['liturg.'],
    'liturgy': ['in full'],
    'london': ['in full'],
    'lord': ['in full', 'exc. when part of a proper name, when > Ld.'],
    'lymphatic': ['in full'],
    'macedonia': ['in full'],
    'machine': ['in full'],
    'machinery': ['in full'],
    'magazine': ['mag.'],
    'magazines': ['mag.'],
    'magistrate': ['in full'],
    'magnetic': ['magn.'],
    'magnetical': ['in full'],
    'magnetisation': ['magn.'],
    'magnetisations': ['magn.'],
    'magnetise': ['magn.'],
    'magnetism': ['in full'],
    'magnetization': ['magn.'],
    'magnetizations': ['magn.'],
    'magnetize': ['magn.'],
    'maintenance': ['in full'],
    'management': ['managem.'],
    'managements': ['managem.'],
    'manager': ['in full'],
    'manchester': ['Manch.'],
    'manchesters': ['Manch.'],
    'manipulation': ['manip.'],
    'manipulations': ['manip.'],
    'manual': ['man.'],
    'manuals': ['man.'],
    'manufacture': ['manuf.'],
    'manufactured': ['manuf.'],
    'manufacturer': ['in full'],
    'manuscript': ['MS'],
    'manuscripts': ['MSS'],
    'marriage': ['in full'],
    'massachusetts': ['Mass.'],
    'massachusettses': ['Mass.'],
    'massacre': ['in full'],
    'materia': ['in full'],
    'mathematical': ['math.'],
    'mathematicals': ['math.'],
    'mathematician': ['in full'],
    'mathematics': ['math.'],
    'measure': ['meas.'],
    'measurement': ['measurem.'],
    'measurements': ['measurem.'],
    'measures': ['meas.'],
    'mechanic': ['mech.', 'exc. person when in full'],
    'mechanical': ['mech.'],
    'mechanicals': ['mech.'],
    'mechanics': ['mech.', 'exc. person when in full'],
    'mechanism': ['in full'],
    'mediaeval': ['in full'],
    'medical': ['med.'],
    'medicinal': ['in full'],
    'medicine': ['med.'],
    'medicines': ['med.'],
    'medieval': ['in full'],
    'meditation': ['medit.'],
    'meditations': ['medit.'],
    'mediterranean': ['in full'],
    'memoir': ['mem.'],
    'memoirs': ['mem.'],
    'memorandum': ['in full'],
    'memorial': ['in full'],
    'memory': ['in full'],
    'merchant': ['in full'],
    'metalliferous': ['metallif.'],
    'metallographer': ['in full'],
    'metallographic': ['metallogr.'],
    'metallographics': ['metallogr.'],
    'metallographies': ['metallogr.'],
    'metallography': ['metallogr.'],
    'metallurgical': ['metall.'],
    'metallurgies': ['metall.'],
    'metallurgist': ['in full'],
    'metallurgy': ['metall.'],
    'metamorphose': ['metamorph.'],
    'metamorphoses': ['metamorph.'],
    'metamorphosis': ['metamorph.'],
    'meteorological': ['meteorol.'],
    'meteorologies': ['meteorol.'],
    'meteorologist': ['in full'],
    'meteorology': ['meteorol.'],
    'metrical': ['in full'],
    'metropolis': ['in full'],
    'metropolitan': ['metrop.'],
    'metropolitana': ['metrop.'],
    'metropolitans': ['metrop.'],
    'michigan': ['Mich.'],
    'michigans': ['Mich.'],
    'microscope': ['in full'],
    'microscopic': ['microsc.'],
    'microscopical': ['microsc.'],
    'microscopies': ['microsc.'],
    'microscopy': ['microsc.'],
    'militaries': ['mil.'],
    'military': ['mil.'],
    'mineral': ['in full'],
    'mineralogical': ['mineral.'],
    'mineralogies': ['mineral.'],
    'mineralogist': ['in full'],
    'mineralogy': ['mineral.'],
    'miniature': ['in full'],
    'minute': ['in full'],
    'miscellaneous': ['misc.'],
    'miscellanies': ['misc.'],
    'miscellany': ['misc.'],
    'moderation': ['in full'],
    'modern': ['mod.'],
    'modernized': ['in full'],
    'monastery': ['in full'],
    'monastic': ['in full'],
    'monastical': ['in full'],
    'monograph': ['monogr.'],
    'monographs': ['monogr.'],
    'monthly': ['in full'],
    'monument': ['in full'],
    'monumental': ['in full'],
    'mount': ['in full', 'exc. when with name, when > Mt./Mts.'],
    'mountain': ['in full', 'exc. when with name, when > Mt./Mts.'],
    'mountaineer': ['in full'],
    'mountaineering': ['in full'],
    'mountains': ['in full', 'exc. when with name, when > Mt./Mts.'],
    'mounts': ['in full', 'exc. when with name, when > Mt./Mts.'],
    'movement': ['in full'],
    'municipal': ['munic.'],
    'muniments': ['munim.'],
    'museum': ['in full', 'exc. in name, when > Mus.'],
    'museums': ['in full', 'exc. in name, when > Mus.'],
    'music': ['in full'],
    'musical': ['in full'],
    'mutual': ['in full'],
    'mysteries': ['myst.'],
    'mystery': ['myst.'],
    'mythologies': ['in full'],
    'narrative': ['narr.'],
    'narratives': ['narr.'],
    'national': ['in full'],
    'natural': ['nat.'],
    'naturalist': ['in full'],
    'nature': ['in full'],
    'nautical': ['naut.'],
    'naval': ['in full'],
    'navigation': ['in full'],
    'navigator': ['in full'],
    'needlework': ['in full'],
    'nervous': ['nerv.'],
    'newsletter': ['newslet.'],
    'newsletters': ['newslett.'],
    'nomenclature': ['nomencl.'],
    'nomenclatures': ['nomencl.'],
    'nonconformism': ['in full'],
    'nonconformist': ['in full'],
    'north': ['in full', 'exc. when with a place-name, when > N.'],
    'northamptonshire': ['Northants.'],
    'northamptonshires': ['Northants.'],
    'northern': ['in full', 'exc. when with a place-name, when > N.'],
    'nottinghamshire': ['Notts.'],
    'nottinghamshires': ['Notts.'],
    'nuclear': ['nucl.'],
    'number': ['in full', 'exc. when in conjunction with figure or spec. jrnl. issue, when > no.'],
    'obedience': ['obed.'],
    'obediences': ['obed.'],
    'observation': ['observ.'],
    'observations': ['observ.'],
    'observer': ['in full'],
    'obstetric': ['obstetr.'],
    'obstetrics': ['obstetr.'],
    'occasion': ['in full'],
    'occasional': ['occas.'],
    'occupation': ['occup.'],
    'occupational': ['occup.'],
    'occupations': ['occup.'],
    'occurrence': ['occurr.'],
    'occurrences': ['occurr.'],
    'oceanographer': ['in full'],
    'oceanographic': ['oceanogr.'],
    'oceanographical': ['oceanogr.'],
    'oceanographies': ['oceanogr.'],
    'oceanography': ['oceanogr.'],
    'official': ['in full'],
    'oklahoma': ['Okla.'],
    'oklahomas': ['Okla.'],
    'ontario': ['Ont.'],
    'ontarios': ['Ont.'],
    'ophthalmologies': ['ophthalmol.'],
    'ophthalmologist': ['in full'],
    'ophthalmology': ['ophthalmol.'],
    'oppression': ['oppress.'],
    'oppressions': ['oppress.'],
    'order': ['in full'],
    'ordinal': ['in full'],
    'ordinance': ['in full'],
    'ordinary': ['in full'],
    'organic': ['org.'],
    'organization': ['in full'],
    'origin': ['in full'],
    'original': ['orig.'],
    'originals': ['orig.'],
    'origination': ['originat.'],
    'originations': ['originat.'],
    'ornithological': ['ornithol.'],
    'ornithologies': ['ornithol.'],
    'ornithologist': ['in full'],
    'ornithology': ['ornithol.'],
    'orthodox': ['in full'],
    'outline': ['outl.'],
    'outlines': ['outl.'],
    'oxford': ['Oxf.'],
    "oxford's": ['in full'],
    'oxfords': ['Oxf.'],
    'paediatric': ['in full'],
    'paediatrics': ['in full'],
    'palaeontologies': ['palaeontol.'],
    'palaeontologist': ['in full'],
    'palaeontology': ['palaeontol.'],
    'paper': ['in full'],
    'paraphrase': ['paraphr.'],
    'paraphrased': ['paraphr.'],
    'paraphrases': ['paraphr.'],
    'parish': ['in full'],
    'parliament': ['parl.'],
    'parliamentary': ['parl.'],
    'parliaments': ['parl.'],
    'particular': ['in full'],
    'patent': ['in full'],
    'pathological': ['pathol.'],
    'pathologies': ['pathol.'],
    'pathologist': ['in full'],
    'pathology': ['pathol.'],
    'pediatrics': ['in full'],
    'peninsula': ['penins.'],
    'peninsulas': ['penins.'],
    'pennsylvania': ['in full', 'exc. when with a place-name, when > Pa.'],
    'pennsylvanias': ['in full', 'exc. when with a place-name, when > Pa.'],
    'perform': ['in full'],
    'performer': ['in full'],
    'period': ['in full'],
    'periodontologies': ['periodontol.'],
    'periodontology': ['periodontol.'],
    'peripheral': ['in full'],
    'permanent': ['in full'],
    'perpetual': ['in full'],
    'persian': ['in full'],
    'personal': ['in full'],
    'personality': ['in full'],
    'personally': ['in full'],
    'persuasion': ['in full'],
    'persuasive': ['in full'],
    'petrographic': ['petrogr.'],
    'petrographics': ['petrogr.'],
    'petrographies': ['petrogr.'],
    'petrography': ['petrogr.'],
    'petroleum': ['in full'],
    'petrologies': ['petrol.'],
    'petrologist': ['in full'],
    'petrology': ['petrol.'],
    'pharmaceutical': ['pharmaceut.'],
    'pharmaceuticals': ['pharmaceut.'],
    'pharmacological': ['pharmacol.'],
    'pharmacologicals': ['pharmacol.'],
    'pharmacologies': ['pharmacol.'],
    'pharmacologist': ['in full'],
    'pharmacology': ['pharmacol.'],
    'pharmacy': ['in full'],
    'philadelphia': ['in full'],
    'philatelist': ['in full'],
    'philately': ['in full'],
    'philological': ['philol.'],
    'philologicals': ['philol.'],
    'philologies': ['philol.'],
    'philology': ['philol.'],
    'philosopher': ['in full'],
    'philosophic': ['philos.'],
    'philosophical': ['philos.'],
    'philosophicals': ['philos.'],
    'philosophies': ['philos.'],
    'philosophy': ['philos.'],
    'phonetic': ['in full'],
    'photograph': ['in full'],
    'photographer': ['in full'],
    'photographic': ['photogr.'],
    'photographical': ['photogr.'],
    'photographics': ['photogr.'],
    'photographies': ['photogr.'],
    'photography': ['photogr.'],
    'physical': ['in full'],
    'physicist': ['in full'],
    'physics': ['in full'],
    'physiological': ['physiol.'],
    'physiologicals': ['physiol.'],
    'physiologies': ['physiol.'],
    'physiologist': ['in full'],
    'physiology': ['physiol.'],
    'pictorial': ['pict.'],
    'picture': ['in full'],
    'poetical': ['poet.'],
    'poeticals': ['poet.'],
    'political': ['polit.'],
    'politics': ['in full'],
    'popular': ['pop.'],
    'population': ['in full'],
    'portugal': ['in full'],
    'posthumous': ['in full'],
    'posthumously': ['posth.'],
    'practical': ['pract.'],
    'practice': ['pract.'],
    'practices': ['pract.'],
    'prediction': ['predict.'],
    'predictions': ['predict.'],
    'preface': ['pref.'],
    'prefaces': ['pref.'],
    'prehistoric': ['in full'],
    'prehistories': ['prehist.'],
    'prehistory': ['prehist.'],
    'prejudice': ['in full'],
    'preparation': ['prepar.'],
    'preparations': ['prepar.'],
    'presbyterian': ['in full'],
    'present': ['in full'],
    'preservation': ['preserv.'],
    'preservations': ['preserv.'],
    'president': ['in full'],
    'presidential': ['in full'],
    'prestressed': ['in full'],
    'prevent': ['in full'],
    'preventative': ['in full'],
    'prevention': ['in full'],
    'primitive': ['in full'],
    'principle': ['princ.'],
    'principles': ['princ.'],
    'private': ['in full'],
    'probability': ['in full'],
    'problem': ['probl.'],
    'problems': ['probl.'],
    'proceedings': ['proc.'],
    'processing': ['in full'],
    'proclamation': ['proclam.'],
    'proclamations': ['proclam.'],
    'production': ['in full'],
    'professor': ['in full'],
    'profitable': ['in full'],
    'progress': ['in full'],
    'prologue': ['prol.'],
    'prologues': ['prol.'],
    'pronunciation': ['pronunc.'],
    'pronunciations': ['pronunc.'],
    'propagation': ['in full'],
    'properties': ['prop.'],
    'property': ['prop.'],
    'prophecy': ['in full'],
    'prophet': ['in full'],
    'prosody': ['in full'],
    'protestant': ['in full'],
    'proverb': ['prov.'],
    'proverbs': ['prov.'],
    'province': ['in full'],
    'provincial': ['provinc.'],
    'provision(s)': ['in full'],
    'provisional': ['in full'],
    'provost': ['in full'],
    'psalm': ['in full'],
    'psychoanalyses': ['psychoanal.'],
    'psychoanalysis': ['psychoanal.'],
    'psychological': ['psychol.'],
    'psychologies': ['psychol.'],
    'psychologist': ['in full'],
    'psychology': ['psychol.'],
    'psychopathological': ['psychopathol.'],
    'psychopathologies': ['psychopathol.'],
    'psychopathologist': ['in full'],
    'psychopathology': ['psychopathol.'],
    'public': ['in full'],
    'publication': ['publ.'],
    'publications': ['publ.'],
    'publisher': ['in full'],
    'quarterlies': ['q.'],
    'quarterly': ['q.'],
    'quartet': ['in full'],
    'queen': ['in full'],
    'question': ['in full'],
    'railway': ['in full'],
    'reader': ['in full'],
    'reading': ['in full'],
    'rebellion': ['in full'],
    'recantation': ['in full'],
    'recent': ['in full'],
    'reclamation': ['reclam.'],
    'reclamations': ['reclam.'],
    'recollection': ['recoll.'],
    'recollections': ['recoll.'],
    'reconnaissance': ['in full'],
    'record': ['rec.', 'exc. in name of newspaper, when in full'],
    'recorder': ['in full'],
    'records': ['rec.', 'exc. in name of newspaper, when in full'],
    'recreation': ['in full'],
    'redemption': ['redempt.'],
    'redemptions': ['redempt.'],
    'reference': ['ref.'],
    'references': ['ref.'],
    'refinery': ['in full'],
    'refining': ['in full'],
    'reflection': ['refl.'],
    'reflections': ['refl.'],
    'reflective': ['refl.'],
    'reformation': ['in full'],
    'reformed': ['in full'],
    'refutation': ['refut.'],
    'refutations': ['refut.'],
    'regiment': ['in full'],
    'register': ['reg.'],
    'registers': ['reg.'],
    'registry': ['in full'],
    'regulations': ['in full'],
    'rehabilitation': ['rehabilit.'],
    'rehabilitations': ['rehabilit.'],
    'relation': ['in full'],
    'relational': ['in full'],
    'relationship': ['in full'],
    'religion': ['relig.'],
    'religions': ['relig.'],
    'religious': ['relig.'],
    'remainder': ['in full'],
    'remains': ['in full'],
    'remarkable': ['in full'],
    'remarks': ['in full'],
    'reminiscence': ['reminisc.'],
    'reminiscences': ['reminisc.'],
    'reminiscent': ['reminisc.'],
    'remonstrance': ['remonstr.'],
    'remonstrances': ['remonstr.'],
    'report': ['rep.'],
    'reporter': ['in full'],
    'reports': ['rep.'],
    'representative': ['in full'],
    'reproduction': ['reprod.'],
    'reproductions': ['reprod.'],
    'reproductive': ['reprod.'],
    'republic': ['in full'],
    'research': ['res.'],
    'researches': ['res.'],
    'residence': ['resid.'],
    'residences': ['resid.'],
    'residential': ['resid.'],
    'residual': ['in full'],
    'resolution': ['resol.'],
    'resolutions': ['resol.'],
    'retrospective': ['retrosp.'],
    'retrospectives': ['retrosp.'],
    'revelation': ['in full'],
    'reviews': ['in full'],
    'revised': ['rev.'],
    'revolution': ['revol.'],
    'revolutions': ['revol.'],
    'roman': ['rom.'],
    'royal': ['in full'],
    'rudiments': ['rudim.'],
    'russia': ['in full'],
    'russian': ['Russ.'],
    'russians': ['Russ.'],
    'sacral': ['in full'],
    'sacred': ['in full'],
    'sacrifice': ['in full'],
    'sacrificial': ['in full'],
    'saint': ['in full', 'exc. foll. by named saint, when > St.'],
    'saints': ['in full', 'exc. foll. by named saints, when > SS.'],
    'saskatchewan': ['Sask.'],
    'saskatchewans': ['Sask.'],
    'saturday': ['Sat.'],
    'saturdays': ['Sat.'],
    'scandinavia': ['Scand.'],
    'scandinavian': ['Scand.'],
    'scandinavians': ['Scand.'],
    'scandinavias': ['Scand.'],
    'school': ['in full'],
    'science': ['sci.'],
    'sciences': ['sci.'],
    'scientific': ['sci.'],
    'scientist': ['in full'],
    'scotch': ['Sc.'],
    'scotches': ['Sc.'],
    'scotland': ['Scotl.'],
    'scotlands': ['Scotl.'],
    'scots': ['in full'],
    'scottish': ['Sc.'],
    'scottishes': ['Sc.'],
    'scripture': ['script.'],
    'scriptures': ['script.'],
    'sculpture': ['sculpt.'],
    'sculptures': ['sculpt.'],
    'seashell': ['in full'],
    'section': ['in full'],
    'security': ['in full'],
    'sedimentary': ['in full'],
    'sedimentation': ['in full'],
    'select': ['in full'],
    'selected': ['sel.'],
    'selection': ['select.'],
    'selections': ['select.'],
    'sermon': ['serm.'],
    'sermons': ['serm.'],
    'service': ['in full'],
    'several': ['in full'],
    'severity': ['in full'],
    'shakespearean': ['in full'],
    'shakspearean': ['in full'],
    'sheffield': ['in full'],
    'sketch': ['in full'],
    'social': ['in full'],
    'society': ['in full', 'exc. as part of named body, when > Soc.'],
    'sociological': ['sociol.'],
    'sociologies': ['sociol.'],
    'sociologist': ['in full'],
    'sociology': ['sociol.'],
    'sonnet': ['in full'],
    'south': ['in full', 'exc. when with a place-name, when > S.'],
    'southern': ['in full', 'exc. when with a place-name, when > S.'],
    'spain': ['in full'],
    'spanish': ['in full'],
    'specification': ['specif.'],
    'specifications': ['specif.'],
    'spectator': ['in full'],
    'speech': ['in full'],
    'spiritual': ['in full'],
    'squire': ['in full'],
    'staffordshire': ['Staffs.'],
    'staffordshires': ['Staffs.'],
    'standard': ['in full'],
    'state': ['in full'],
    'statistical': ['statist.'],
    'statistics': ['in full'],
    'statutes': ['in full'],
    'strange': ['in full'],
    'stranger': ['in full'],
    'stratigrapher': ['in full'],
    'stratigraphic': ['stratigr.'],
    'stratigraphics': ['stratigr.'],
    'stratigraphies': ['stratigr.'],
    'stratigraphy': ['stratigr.'],
    'street': ['in full', 'exc. when part of a name, when > St.'],
    'strong': ['in full'],
    'stronger': ['in full'],
    'structural': ['struct.'],
    'structure': ['struct.'],
    'structured': ['struct.'],
    'structures': ['struct.'],
    'studies': ['stud.'],
    'study': ['in full'],
    'subject': ['subj.'],
    'subjects': ['subj.'],
    'substance': ['in full'],
    'sunday': ['in full'],
    'supplement': ['suppl.'],
    'supplements': ['suppl.'],
    'surgeon': ['in full'],
    'surgeries': ['surg.'],
    'surgery': ['surg.'],
    'surgical': ['surg.'],
    'survey': ['surv.'],
    'surveying': ['surv.'],
    'surveyor': ['in full'],
    'surveys': ['surv.'],
    'survival': ['in full'],
    'survive': ['in full'],
    'surviving': ['in full'],
    'survivor': ['in full'],
    'symbolic': ['in full'],
    'symbolical': ['in full'],
    'symbolism': ['in full'],
    'symbolist': ['in full'],
    'symposia': ['symp.'],
    'symposium': ['symp.'],
    'synopsis': ['in full'],
    'system': ['syst.'],
    'systematic': ['in full'],
    'systems': ['syst.'],
    'taxonomic': ['taxon.'],
    'taxonomies': ['taxon.'],
    'taxonomist': ['in full'],
    'taxonomy': ['taxon.'],
    'technical': ['techn.'],
    'technique': ['in full'],
    'technological': ['technol.'],
    'technologies': ['technol.'],
    'technologist': ['in full'],
    'technology': ['technol.'],
    'telecommunication': ['in full'],
    'telecommunications': ['in full'],
    'telegraph': ['telegr.', 'exc. In newspaper titles, when Tel.'],
    'telegraphic': ['telegr.'],
    'telegraphics': ['telegr.'],
    'telegraphies': ['telegr.'],
    'telegraphist': ['in full'],
    'telegraphs': ['telegr.', 'exc. In newspaper titles, when Tel.'],
    'telegraphy': ['telegr.'],
    'telephone': ['in full'],
    'telephonic': ['teleph.'],
    'telephonics': ['teleph.'],
    'telephonies': ['teleph.'],
    'telephony': ['teleph.'],
    'television': ['TV'],
    'televisions': ['TV'],
    'televisual': ['in full'],
    'terminologies': ['terminol.'],
    'terminology': ['terminol.'],
    'terrestrial': ['terrestr.'],
    'terrestrials': ['terrestr.'],
    'terrible': ['in full'],
    'territorial': ['in full'],
    'territory': ['in full'],
    'testament': ['test.'],
    'testaments': ['test.'],
    'testing': ['in full'],
    'text-book': ['text-bk.'],
    'text-books': ['text-bk.'],
    'textbook': ['textbk.'],
    'textbooks': ['textbk.'],
    'thanksgiving': ['in full'],
    'theatre': ['in full'],
    'theatrical': ['theatr.'],
    'theatricals': ['theatr.'],
    'theologian': ['in full'],
    'theological': ['theol.'],
    'theologies': ['theol.'],
    'theology': ['theol.'],
    'theoretical': ['theoret.'],
    'theoreticals': ['theoret.'],
    'theories': ['in full'],
    'theory': ['in full'],
    'therapist': ['in full'],
    'therapy': ['in full'],
    'thermodynamics': ['in full'],
    'thesaurus': ['thes.'],
    'thesauruses': ['thes.'],
    'tractate': ['in full'],
    'tradition': ['trad.'],
    'traditional': ['trad.'],
    'traditionalist': ['in full'],
    'traditionals': ['trad.'],
    'traditions': ['trad.'],
    'tragedie': ['trag.'],
    'tragedies': ['trag.'],
    'tragedy': ['trag.'],
    'tragic': ['in full'],
    'transaction': ['trans.'],
    'transactions': ['trans.'],
    'transfer': ['in full'],
    'transform': ['in full'],
    'transformation': ['in full'],
    'translation': ['transl.'],
    'translations': ['transl.'],
    'transubstantiation': ['transubstant.'],
    'transubstantiations': ['transubstant.'],
    'travel': ['trav.'],
    'travels': ['trav.'],
    'treasure': ['in full'],
    'treasury': ['in full'],
    'treatise': ['treat.'],
    'treatises': ['treat.'],
    'treatment': ['treatm.'],
    'treatments': ['treatm.'],
    'tributary': ['in full'],
    'trigonometries': ['trigonom.'],
    'trigonometry': ['trigonom.'],
    'triumph': ['in full'],
    'triumphal': ['in full'],
    'tropical': ['trop.'],
    'tropics': ['in full'],
    'undergraduate': ['in full'],
    'understanding': ['in full'],
    'universal': ['in full'],
    'universe': ['in full'],
    'universities': ['in full', 'exc. as part of named body, when > univ.'],
    'university': ['in full', 'exc. as part of named body, when > univ.'],
    'unofficial': ['unoffic.'],
    'unreformed': ['in full'],
    'urinary': ['urin.'],
    'utilitarian': ['utilit.'],
    'utilitarians': ['utilit.'],
    'vacation': ['vac.'],
    'vacations': ['vac.'],
    'valediction': ['in full'],
    'variable': ['in full'],
    'variant': ['in full'],
    'variation': ['in full'],
    'variational': ['in full'],
    'variety': ['in full'],
    'various': ['var.'],
    'vegetable': ['veg.'],
    'vegetables': ['veg.'],
    'vegetarian': ['in full'],
    'vegetation': ['in full'],
    'vertebrate': ['vertebr.'],
    'vertebrates': ['vertebr.'],
    'veterinarian': ['in full'],
    'veterinaries': ['vet.'],
    'veterinary': ['vet.'],
    'victor': ['in full'],
    'victorian': ['in full'],
    'victorious': ['in full'],
    'victory': ['in full'],
    'vindicated': ['in full'],
    'vindication': ['vindic.'],
    'vindications': ['vindic.'],
    'virginia': ['in full', 'exc. when with a place-name, when > Va.'],
    'virginias': ['in full', 'exc. when with a place-name, when > Va.'],
    'visibility': ['in full'],
    'vision': ['in full'],
    'vocabularies': ['vocab.'],
    'vocabulary': ['vocab.'],
    'vocational': ['in full'],
    'voyage': ['voy.'],
    'voyages': ['voy.'],
    'wandering': ['in full'],
    'weekly': ['in full'],
    'west': ['in full', 'exc. when with a place-name, when > W.'],
    'western': ['in full', 'exc. when with a place-name, when > W.'],
    'westminster': ['Westm.'],
    'westminsters': ['Westm.'],
    'wiltshire': ['Wilts.'],
    'wiltshires': ['Wilts.'],
    'woodland': ['in full'],
    'worcestershire': ['Worcs.'],
    'worcestershires': ['Worcs.'],
    'word': ['in full'],
    'work': ['in full'],
    'works': ['wks.'],
    'year': ['in full'],
    'yorkshire': ['Yorks.'],
    'yorkshires': ['Yorks.'],
    'young': ['in full'],
    'zoological': ['zool.'],
    'zoologies': ['zool.'],
    'zoologist': ['in full'],
    'zoology': ['zool.']
}


function* ngrams(a, n) { 
    let buf = [];

    for (let x of a) {
        buf.push(x);
        if (buf.length === n) {
            yield buf;
            buf.shift();
        }
    }
}


function abbreviate(string) {
    let abbObject = {
        title: '',
        notes: []
    }

    //slice off anything after a colon (i.e. subtitles)

    //check if title is more than one word, else skip to just assigning string to object
    if (string.includes(' ')) {
        string = string.toLowerCase()
        
        array = string.split(' ')

        //REPLACE QUADGRAMS
        let quads = []
        for (let g of ngrams(array, 4))
        quads.push(g.join(' '))

        for (var i=0; i < quads.length; i++) {
            if (quads[i] in quadgrams) {
                string = string.replace(quads[i], quadgrams[quads[i]])
                array = string.split(' ')
            }
        }

        //REPLACE TRIGRAMS
        let tris = []
        for (let g of ngrams(array, 3))
        tris.push(g.join(' '))

        for (var i=0; i < tris.length; i++) {
            if (tris[i] in trigrams) {
                string = string.replace(tris[i], trigrams[tris[i]])
                array = string.split(' ')
            }
        }

        //REPLACE BIGRAMS
        let bis = []
        for (let g of ngrams(array, 2))
        bis.push(g.join(' '))

        for (var i=0; i < bis.length; i++) {
            if (bis[i] in bigrams) {
                if (bigrams[bis[i]][0] != 'in full') {
                    string = string.replace(bis[i], bigrams[bis[i]][0])
                    array = string.split(' ')
                }
                if (bigrams[bis[i]].length > 1) {
                    abbObject.notes.push(bigrams[bis[i]][1])
                }
            }
        }

        //REPLACE UNIGRAMS
        for (var i=0; i < array.length; i++) {
            if (array[i] in unigrams) {

                if (unigrams[array[i]][0] != 'in full') {
                    string = string.replace(array[i], unigrams[array[i]][0])
                } 
                if (unigrams[array[i]].length > 1) {
                    abbObject.notes.push(unigrams[array[i]][1])
                }
            }
        }

        //remove common first words
        const firstwords = ['the', 'an', 'a']
        array = string.split(' ')
        if (firstwords.includes(array[0])) {
            string = array.slice(1).join(' ')
        }

        //TODO: do general rules (-ment endings etc); see block below
        //currently losing capitals after punctation e.g. U.s., (london) etc
        // need to make list of plurals and add to abbreviations.


        // General rules:
        // Do not abbreviate the 1st word of a title unless it is a fairly common one.
        // Do not abbreviate a single-word title, unless it a) is preceded by an author's name and b) consists of a very common OED abbreviation.
        // Words ending "-ment" should usu. be abbreviated to "-m.", as in Arrangem. Exceptions such as "experiment" are listed here.
        // Words ending "-olog-" should be abbreviated to "-ol.", so that both Biology and Biological become Biol.
        // Words ending "-ograph-" should usually be abbreviated to "-ogr." (but see "geographic", below). Words ending in "-ographer" (e.g. "photographer") are not abbreviated.
        // Prepositions will not be abbreviated (though they may be omitted).
        // Personal names will not be abbreviated exc. in biographical titles.
        // Plural forms are abbrev. in the same way as singular, unless listed below.
        // Hyphenated compounds: the second element is not capitalized, unless it's in the title of two merged newspapers, e.g. Courier-Mail.


        // other bits and pieces

        //remove the, prepositions etc

        //replace and with &
        if (string.includes(' and ')) {
        string = string.replace(' and ', ' & ')
        }

        //finally, make initial letters uppercase
        // NB this currently doesn't catch letters before opening brackets, and any uppercase from acronyms/initials is lost too
        //so use a regex
        //NB dont capitalise second elemnt of hyphenated compound, as in rules above
        let words = string.split(" ");
        for (let i = 0; i < words.length; i++) {
            words[i] = words[i][0].toUpperCase() + words[i].substr(1);
        }
        string = words.join(" ");


        //assign end product to object
        abbObject.title = string
        
    } else {
        abbObject.title = string
        abbObject.notes.push("Do not abbreviate a single-word title, unless it a) is preceded by an author's name and b) consists of a very common OED abbreviation.")
    }

    return abbObject
}

